### ISSUE TITLE
develop: Incorrect errors (Undeclared reference: ...) reported, although the build succeeds without any issues

### ISSUE THREAD

**Issue by Dima-369** [obiwan87/odin-intellij#48]
I tested with your repo: https://github.com/obiwan87/odin-examples

And it shows those errors, although the build succeeds, which is quite confusing:

![CleanShot 2024-08-13 at 16 26 53@2x](https://github.com/user-attachments/assets/18bd3e3b-2245-4aa0-ab29-ca6087dabf62)

![CleanShot 2024-08-13 at 16 30 40@2x](https://github.com/user-attachments/assets/6de6e2ea-baa0-41d5-8159-2d69784da9ef)

**Comment by obiwan87** [comment]
Yes, I've already fixed that specific failure. But in any case, that's what I meant in https://github.com/obiwan87/odin-intellij/issues/44#issuecomment-2283376647. The checker is not done yet, and so it fails with built-in stuff like any, typeinfo, make, etc. Since we have the "odin check" method now, I will disable the reference checker for 0.5.0 :)

**Comment by obiwan87** [comment]
Disabled reference checker with commit 9d4e955 and fixed raylib.Color failure with 4bdbca8
